USE [master]
GO

/****** Object:  Database [CVUploderDB]    Script Date: 11/10/2020 8:40:29 AM ******/
CREATE DATABASE [CVUploderDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CVUploderDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\CVUploderDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CVUploderDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\CVUploderDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CVUploderDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CVUploderDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CVUploderDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CVUploderDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CVUploderDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CVUploderDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [CVUploderDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CVUploderDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CVUploderDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CVUploderDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CVUploderDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CVUploderDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CVUploderDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CVUploderDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CVUploderDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CVUploderDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [CVUploderDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CVUploderDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CVUploderDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CVUploderDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CVUploderDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CVUploderDB] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [CVUploderDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CVUploderDB] SET RECOVERY FULL 
GO

ALTER DATABASE [CVUploderDB] SET  MULTI_USER 
GO

ALTER DATABASE [CVUploderDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CVUploderDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CVUploderDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CVUploderDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CVUploderDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CVUploderDB] SET QUERY_STORE = OFF
GO

USE [CVUploderDB]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [CVUploderDB] SET  READ_WRITE 
GO

